# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'
# Optionally set API keys here instead of exporting environment variables.
# Never commit real keys to source control.
env:
  GOOGLE_API_KEY: "AIzaSyC2sfVaGPbenLsQigQW4djc4M9g9NHO6PU"
prompts:
  - 'Convert this English to {{language}}: {{input}}'
  - 'Translate to {{language}}: {{input}}'

providers:
   - "google:gemini-2.5-flash-lite"

tests:
  - vars:
      language: French
      input: Hello world
    assert:
      - type: contains
        value: 'Bonjour le monde'
  - vars:
      language: Spanish
      input: Where is the library?
    assert:
      - type: icontains
        value: 'Dónde está la biblioteca'
